### ISSUE TITLE
elasticsearch-client-rest plugin causes authorization failed error

### ISSUE THREAD

**Issue by randallt** [opentracing-contrib/java-elasticsearch-client#17]
When instrumenting an application that uses Java Elasticsearch High-level REST client, the specialagent elasticsearch-client-rest plugin causes the request to error out with a 401 unauthorized response. It appears that the plugin is somehow preventing the authentication/authorization mechanism from functioning correctly. When I explicitly disable just the "elasticsearch:client-rest" plugin, then it works as expected (but no span for elastic search, of course).

```
2019-11-18 15:25:00,14588 org.elasticsearch.ElasticsearchStatusException: Unable to parse response body
2019-11-18 15:25:00,14588       at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2030)
2019-11-18 15:25:00,14589       at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1775)
2019-11-18 15:25:00,14589       at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1732)
2019-11-18 15:25:00,14591       at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1694)
2019-11-18 15:25:00,14592       at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1090)
...
2019-11-18 15:25:00,14668       at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
2019-11-18 15:25:00,14668       at java.lang.Thread.run(Thread.java:748)
2019-11-18 15:25:00,14669       Suppressed: java.lang.IllegalStateException: Unsupported Content-Type: text/plain; charset=UTF-8
2019-11-18 15:25:00,14669               at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2047)
2019-11-18 15:25:00,14671               at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2026)
2019-11-18 15:25:00,14671               ... 126 common frames omitted
2019-11-18 15:25:00,14672 Caused by: org.elasticsearch.client.ResponseException: method [POST], host [https://example.net:9200], URI [/r_resolved_events/_search?typed_keys=true&allow_partial_search_results=false&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&search_type=query_then_fetch&batched_reduce_size=512], status line [HTTP/1.1 401 Unauthorized]
2019-11-18 15:25:00,14673 Unauthorized
2019-11-18 15:25:00,14673       at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:929)
2019-11-18 15:25:00,14674       at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229)
2019-11-18 15:25:00,14674       at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1762)
2019-11-18 15:25:00,14676       ... 125 common frames omitted
2019-11-18 15:25:00,14676 Caused by: org.elasticsearch.client.ResponseException: method [POST], host [https://example.net:9200], URI [/r_resolved_events/_search?typed_keys=true&allow_partial_search_results=false&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&search_type=query_then_fetch&batched_reduce_size=512], status line [HTTP/1.1 401 Unauthorized]
2019-11-18 15:25:00,14678 Unauthorized
2019-11-18 15:25:00,14678       at org.elasticsearch.client.RestClient$1.completed(RestClient.java:548)
2019-11-18 15:25:00,14679       at org.elasticsearch.client.RestClient$1.completed(RestClient.java:533)
2019-11-18 15:25:00,14679       at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123)
2019-11-18 15:25:00,14680       at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
2019-11-18 15:25:00,14680       at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:439)
2019-11-18 15:25:00,14681       at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:329)
2019-11-18 15:25:00,14681       at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
2019-11-18 15:25:00,14682       at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
2019-11-18 15:25:00,14682       at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
2019-11-18 15:25:00,14683       at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
2019-11-18 15:25:00,14684       at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
2019-11-18 15:25:00,14684       at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
2019-11-18 15:25:00,14685       at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
2019-11-18 15:25:00,14685       at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
2019-11-18 15:25:00,14686       at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
2019-11-18 15:25:00,14686       at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
2019-11-18 15:25:00,14687       ... 1 common frames omitted
```

And the elasticsearch client version is 6.6.1

```
elasticsearch-6.6.1.jar
elasticsearch-cli-6.6.1.jar
elasticsearch-core-6.6.1.jar
elasticsearch-rest-client-6.6.1.jar
elasticsearch-rest-high-level-client-6.6.1.jar
elasticsearch-secure-sm-6.6.1.jar
elasticsearch-x-content-6.6.1.jar
```

This is running in a Spring Boot v2.0.3.RELEASE application (static deferred attach automatically enable).

I am running my own custom specialagent, but I just sync'ed it to version 1.5.1 of this project.

**Comment by randallt** [comment]
Please transfer this issue back to the java-specialagent.

It looks like this is the problem:

```
public class ElasticsearchRestClientAgentIntercept {
  public static void rest(final Object thiz) {
    ((RestClientBuilder)thiz).setHttpClientConfigCallback(new TracingHttpClientConfigCallback());
  }
}
```

Our code uses RestClientBuilder.setHttpClientConfigCallback to configure the credentials provider and the SSL context. So it looks like this instrumentation is clobbering that. Seems like a pretty big bug here. Needs to somehow be a wrapper to any existing config callback. I'll see if I can find a quick solution to recommend.

**Comment by randallt** [comment]
Looks like this patch fixes the issue:

```
diff --git a/rule/elasticsearch-client-rest/src/main/java/io/opentracing/contrib/specialagent/rule/elasticsearch/rest/ElasticsearchRestClientAgentIntercept.java b/rule/elasticsearch-client-rest/src/main/java/io/opentracing/contrib/specialagent/rule/elasticsearch/rest/ElasticsearchRestClientAgentIntercept.java
index 618a1c9..c6ba7ec 100644
--- a/rule/elasticsearch-client-rest/src/main/java/io/opentracing/contrib/specialagent/rule/elasticsearch/rest/ElasticsearchRestClientAgentIntercept.java
+++ b/rule/elasticsearch-client-rest/src/main/java/io/opentracing/contrib/specialagent/rule/elasticsearch/rest/ElasticsearchRestClientAgentIntercept.java
@@ -16,11 +16,12 @@
 package io.opentracing.contrib.specialagent.rule.elasticsearch.rest;
 
 import org.elasticsearch.client.RestClientBuilder;
+import org.elasticsearch.client.RestClientBuilder.HttpClientConfigCallback;
 
 import io.opentracing.contrib.elasticsearch.common.TracingHttpClientConfigCallback;
 
 public class ElasticsearchRestClientAgentIntercept {
-  public static void rest(final Object thiz) {
-    ((RestClientBuilder)thiz).setHttpClientConfigCallback(new TracingHttpClientConfigCallback());
+  public static void rest(final Object thiz, final Object existingHttpClientConfigCallback) {
+    ((RestClientBuilder)thiz).setHttpClientConfigCallback(new TracingHttpClientConfigCallback((HttpClientConfigCallback)existingHttpClientConfigCallback));
   }
 }
\ No newline at end of file
diff --git a/rule/elasticsearch-client-rest/src/main/java/io/opentracing/contrib/specialagent/rule/elasticsearch/rest/ElasticsearchRestClientAgentRule.java b/rule/elasticsearch-client-rest/src/main/java/io/opentracing/contrib/specialagent/rule/elasticsearch/rest/ElasticsearchRestClientAgentRule.java
index 66bd150..2f3d71c 100644
--- a/rule/elasticsearch-client-rest/src/main/java/io/opentracing/contrib/specialagent/rule/elasticsearch/rest/ElasticsearchRestClientAgentRule.java
+++ b/rule/elasticsearch-client-rest/src/main/java/io/opentracing/contrib/specialagent/rule/elasticsearch/rest/ElasticsearchRestClientAgentRule.java
@@ -25,6 +25,7 @@
 import net.bytebuddy.asm.Advice;
 import net.bytebuddy.description.type.TypeDescription;
 import net.bytebuddy.dynamic.DynamicType.Builder;
+import net.bytebuddy.implementation.bytecode.assign.Assigner;
 import net.bytebuddy.utility.JavaModule;
 
 public class ElasticsearchRestClientAgentRule extends AgentRule {
@@ -41,9 +42,12 @@
 
   public static class Rest {
     @Advice.OnMethodEnter
-    public static void enter(final @Advice.Origin String origin, final @Advice.This Object thiz) {
+    public static void enter(
+    		final @Advice.Origin String origin, 
+    		final @Advice.This Object thiz, 
+    		@Advice.FieldValue(value = "httpClientConfigCallback", readOnly = true, typing = Assigner.Typing.DYNAMIC) Object existingHttpClientConfigCallback) {
       if (isEnabled(origin))
-        ElasticsearchRestClientAgentIntercept.rest(thiz);
+        ElasticsearchRestClientAgentIntercept.rest(thiz, existingHttpClientConfigCallback);
     }
   }
 }
\ No newline at end of file
```

**Comment by randallt** [comment]
Again, this issue belongs back at java-specialagent. @SevaSafris , @malafeev
